name: Spin Potato Animation
on:
  schedule:
    - cron: "*/5 * * * *"  # Update every 5 minutes
  workflow_dispatch:

jobs:
  animate-potato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Rotate Potato
        run: |
          # Get current frame
          if [ -f .github/potato-frames/current ]; then
            CURRENT_FRAME=$(cat .github/potato-frames/current)
            NEW_FRAME=$(( (CURRENT_FRAME % 8) + 1 ))
          else
            NEW_FRAME=1
          fi

          # Save new frame number
          echo $NEW_FRAME > .github/potato-frames/current
          
          # Update README
          FRAME_CONTENT=$(cat .github/potato-frames/frame$NEW_FRAME.txt)
          awk -v content="$FRAME_CONTENT" \
            '/<!-- POTATO START -->/{p=1; print; print content; next} \
             /<!-- POTATO END -->/{p=0} \
             !p' README.md > temp.md && mv temp.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🥔 Spin potato frame $NEW_FRAME"
          file_pattern: README.md .github/potato-frames/current
