name: Spinning Potato
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Generate frames
        run: |
          mkdir frames
          cat <<EOF > frame1.txt
   __
 (    )
(      )
 (____)
EOF
          cat <<EOF > frame2.txt
     __
   (    )
  (      )
   (____)
EOF
          cat <<EOF > frame3.txt
  __
(    )
(      )
 (____)
EOF
          cat <<EOF > frame4.txt
__
(    )
(      )
(____)
EOF
          i=0
          for f in frame1.txt frame2.txt frame3.txt frame4.txt; do
            convert -background white -fill black -font Courier -size 200x100 label:"$(cat $f)" frames/frame_$i.png
            ((i++))
          done
      - name: Create potato.gif
        run: convert -delay 50 -loop 0 frames/*.png potato.gif
      - name: Commit animation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add potato.gif
          git commit -m "Update Potato Animation" || echo "No changes to commit"
          git push
