name: Spin That Potato!
on:
  schedule:
    - cron: "*/7 * * * *"  # Runs every 7 minutes
  workflow_dispatch:

jobs:
  animate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create/Rotate Spud
        run: |
          mkdir -p .github/potato-frames
          if [ ! -f .github/potato-frames/current ]; then
            echo "0" > .github/potato-frames/current
          fi

          echo ' .-~~^~~-.' > .github/potato-frames/frame1.txt
          echo ' ( )' >> .github/potato-frames/frame1.txt
          echo ' > <' >> .github/potato-frames/frame1.txt
          echo "'.___...__.'" >> .github/potato-frames/frame1.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame1.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame1.txt
          echo ' ⌄ ⌄' >> .github/potato-frames/frame1.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame2.txt
          echo ' ( ╱ )' >> .github/potato-frames/frame2.txt
          echo ' > \\ <' >> .github/potato-frames/frame2.txt
          echo "'.___...__.'" >> .github/potato-frames/frame2.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame2.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame2.txt
          echo ' ⌄' >> .github/potato-frames/frame2.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame3.txt
          echo ' ( ⌄ )' >> .github/potato-frames/frame3.txt
          echo ' > ╱╲ <' >> .github/potato-frames/frame3.txt
          echo "'.___...__.'" >> .github/potato-frames/frame3.txt
          echo ' ╲╱' >> .github/potato-frames/frame3.txt
          echo ' ╳' >> .github/potato-frames/frame3.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame3.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame4.txt
          echo ' ( )' >> .github/potato-frames/frame4.txt
          echo ' > ╲╱ <' >> .github/potato-frames/frame4.txt
          echo "'.___...__.'" >> .github/potato-frames/frame4.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame4.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame4.txt
          echo ' ⌄ ⌄' >> .github/potato-frames/frame4.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame5.txt
          echo ' ( ⌄ )' >> .github/potato-frames/frame5.txt
          echo ' > ╱ <' >> .github/potato-frames/frame5.txt
          echo "'.___...__.'" >> .github/potato-frames/frame5.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame5.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame5.txt
          echo ' ⌄ ⌄' >> .github/potato-frames/frame5.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame6.txt
          echo ' ( )' >> .github/potato-frames/frame6.txt
          echo ' > ╱ <' >> .github/potato-frames/frame6.txt
          echo "'.___...__.'" >> .github/potato-frames/frame6.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame6.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame6.txt
          echo ' ⌄ ⌄' >> .github/potato-frames/frame6.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame7.txt
          echo ' ( )' >> .github/potato-frames/frame7.txt
          echo '>╱ <' >> .github/potato-frames/frame7.txt
          echo "'.___...__.'" >> .github/potato-frames/frame7.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame7.txt
          echo ' ╱ ╲' >> .github/potato-frames/frame7.txt
          echo '⌄ ⌄' >> .github/potato-frames/frame7.txt

          echo ' .-~~^~~-.' > .github/potato-frames/frame8.txt
          echo ' ( )' >> .github/potato-frames/frame8.txt
          echo ' >\\ <' >> .github/potato-frames/frame8.txt
          echo "'.___...__.'" >> .github/potato-frames/frame8.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame8.txt
          echo ' ╲ ╱' >> .github/potato-frames/frame8.txt
          echo ' ⌄ ⌄' >> .github/potato-frames/frame8.txt

          # Now rotate
          FRAME_FILE=".github/potato-frames/current"
          CURRENT=$(cat "$FRAME_FILE")
          NEW=$(( (CURRENT % 8) + 1 ))
          echo "$NEW" > "$FRAME_FILE"

          FRAME_CONTENT=$(cat ".github/potato-frames/frame${NEW}.txt")

          perl -i -pe 'BEGIN{undef $/;} s/<!-- POTATO START -->.*<!-- POTATO END -->/<!-- POTATO START -->\n```\n$ENV{FRAME_CONTENT}\n```\n<!-- POTATO END -->/smg' README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🥔 Potato Rotation Frame $NEW"
          branch: main
